openapi: 3.0.0
info:
  contact:
    email: developer-support-pxcloud@cisco.com
    name: API Support
    url: https://cisco.com
  description: CX Partner Portal APIs for the Partners. These APIs are subjected to
    change in the month of August.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://cisco.com
  title: CX Partner Portal APIs
  version: "1.0"
servers:
- description: US Prod Environment
  url: https://api-cx.cisco.com/px
  x-external-backend:
    serviceType: ExternalName
    serviceProtocol: https
    servicePort: 443
    externalName: api-cx.cisco.com
    basePath: /px
tags:
- description: Insights-Compliance-APIs
  name: Compliance
paths:
  /v1/customers/{customerId}/insights/compliance/optIn:
    get:
      deprecated: false
      description: Returns information about whether the customer has successfully
        configured the regulatory compliance feature and has assets that are qualified
        to be checked.
      operationId: getOptInUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/optInResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: optIn status
      tags:
      - Compliance
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/compliance/violations:
    get:
      deprecated: false
      description: "Returns information about the rules violated for the customerId\
        \ provided Default sorting is, severityId(asc), violationCount(desc)"
      operationId: getViolationSummaryUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: The number of items to skip before starting to collect the result
          set. The default value is 1.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      - description: The maximum number of items to return. The default value is 10.
        explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViolationSummaryResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Get the violation summary of a customer
      tags:
      - Compliance
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/compliance/violations/assets:
    get:
      deprecated: false
      description: "Returns information about the customer assets in violation of\
        \ the rule based on the customer, policy, and rule information provided. Default\
        \ sorting is, assetName(asc)"
      operationId: getAssetViolationDetailsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: policyCategory
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: policyGroupId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: policyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: ruleId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: severity
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetsViolationsResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: "Get the violation details of impacted assets for the customer, and\
        \ selected policy Group, Policy and Rule"
      tags:
      - Compliance
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/compliance/policyRuleDetails:
    get:
      deprecated: false
      description: Returns information about the policy the rule belongs to.
      operationId: getPolicyRuleDetailsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: policyCategory
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: policyGroupId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: policyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: ruleId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: severity
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyRuleDetails'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Returns information about the policy the rule belongs to
      tags:
      - Compliance
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/compliance/suggestions:
    get:
      deprecated: false
      description: "Returns information about the violated rule conditions, including\
        \ suggested remediation steps, based on the customer, policy, and rule information\
        \ provided. Default sorting is severityId(desc)"
      operationId: getSuggestionsUsingGET
      parameters:
      - explode: true
        in: query
        name: policyCategory
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: policyGroupId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: policyId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: ruleId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuggestionsResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: "Get the Suggestions filtered upon Severity (if given), for summary\
        \ tab"
      tags:
      - Compliance
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/compliance/assetsWithViolations:
    get:
      deprecated: false
      description: "Returns information about assets that have at least one rule violation\
        \ based on the customerId provided. Default is severityId(desc), violationCount(desc)"
      operationId: getAssetWithViolationsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetsWithViolationsResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Get the asset summary
      tags:
      - Compliance
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/compliance/assetViolations:
    get:
      deprecated: false
      description: Returns information about the rules violated by an asset based
        on the customer and asset information provided. Default is ruleSeverityId(desc)
      operationId: getAssetViolationsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: sourceSystemId
        required: true
        schema:
          type: string
        style: form
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: assetId
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetViolationsResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Get the violations of the asset
      tags:
      - Compliance
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
components:
  schemas:
    ViolationSummaryResponse:
      example:
        totalCount: 0
        items:
        - severity: severity
          ruleTitle: ruleTitle
          violationCount: 6
          policyCategory: policyCategory
          policyId: policyId
          policyName: policyName
          policyGroupName: policyGroupName
          policyGroupId: policyGroupId
          affectedAssetsCount: 1
          severityId: severityId
          ruleId: ruleId
        - severity: severity
          ruleTitle: ruleTitle
          violationCount: 6
          policyCategory: policyCategory
          policyId: policyId
          policyName: policyName
          policyGroupName: policyGroupName
          policyGroupId: policyGroupId
          affectedAssetsCount: 1
          severityId: severityId
          ruleId: ruleId
      properties:
        totalCount:
          description: total Number of violations
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/violationSummary'
          type: array
      title: ViolationSummaryResponse
      type: object
    violationSummary:
      example:
        severity: severity
        ruleTitle: ruleTitle
        violationCount: 6
        policyCategory: policyCategory
        policyId: policyId
        policyName: policyName
        policyGroupName: policyGroupName
        policyGroupId: policyGroupId
        affectedAssetsCount: 1
        severityId: severityId
        ruleId: ruleId
      properties:
        severity:
          type: string
        severityId:
          type: string
        policyGroupId:
          type: string
        policyGroupName:
          type: string
        policyId:
          type: string
        policyName:
          type: string
        ruleId:
          type: string
        ruleTitle:
          type: string
        violationCount:
          format: int64
          type: integer
        affectedAssetsCount:
          format: int64
          type: integer
        policyCategory:
          type: string
      title: violationSummary
      type: object
    AssetsViolationsResponse:
      example:
        totalCount: 0
        items:
        - productFamily: productFamily
          severity: severity
          violationCount: 6
          productId: productId
          softwareType: softwareType
          assetId: assetId
          ipAddress: ipAddress
          assetName: assetName
          scanStatus: true
          softwareRelease: softwareRelease
          lastChecked: lastChecked
        - productFamily: productFamily
          severity: severity
          violationCount: 6
          productId: productId
          softwareType: softwareType
          assetId: assetId
          ipAddress: ipAddress
          assetName: assetName
          scanStatus: true
          softwareRelease: softwareRelease
          lastChecked: lastChecked
      properties:
        totalCount:
          description: total Number of violations
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/AssetsViolations'
          type: array
      title: AssetsViolationsResponse
      type: object
    AssetsViolations:
      example:
        productFamily: productFamily
        severity: severity
        violationCount: 6
        productId: productId
        softwareType: softwareType
        assetId: assetId
        ipAddress: ipAddress
        assetName: assetName
        scanStatus: true
        softwareRelease: softwareRelease
        lastChecked: lastChecked
      properties:
        assetId:
          type: string
        assetName:
          type: string
        ipAddress:
          type: string
        softwareType:
          type: string
        softwareRelease:
          type: string
        productFamily:
          type: string
        productId:
          type: string
        severity:
          type: string
        lastChecked:
          type: string
        scanStatus:
          type: boolean
        violationCount:
          format: int64
          type: integer
      title: AssetsViolations
      type: object
    PolicyRuleDetails:
      example:
        policyDescription: policyDescription
        policyId: policyId
        policyName: policyName
        ruleId: ruleId
      properties:
        policyName:
          type: string
        policyDescription:
          type: string
        policyId:
          type: string
        ruleId:
          type: string
      title: PolicyRuleDetails
      type: object
    Suggestion:
      example:
        severity: severity
        suggestion: suggestion
        affectedAssetsCount: 6
        violationMessage: violationMessage
      properties:
        severity:
          type: string
        violationMessage:
          type: string
        suggestion:
          type: string
        affectedAssetsCount:
          format: int64
          type: integer
      title: Suggestion
      type: object
    SuggestionsResponse:
      example:
        totalCount: 0
        items:
        - severity: severity
          suggestion: suggestion
          affectedAssetsCount: 6
          violationMessage: violationMessage
        - severity: severity
          suggestion: suggestion
          affectedAssetsCount: 6
          violationMessage: violationMessage
      properties:
        totalCount:
          description: total Number of violations
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/Suggestion'
          type: array
      title: SuggestionsResponse
      type: object
    AssetsWithViolations:
      example:
        severity: severity
        serialNumber: serialNumber
        violationCount: 6
        softwareType: softwareType
        assetId: assetId
        ipAddress: ipAddress
        assetName: assetName
        scanStatus: true
        softwareRelease: softwareRelease
        severityId: severityId
        lastChecked: 2000-01-23T04:56:07.000+00:00
      properties:
        assetId:
          type: string
        assetName:
          type: string
        ipAddress:
          type: string
        softwareType:
          type: string
        serialNumber:
          type: string
        softwareRelease:
          type: string
        severity:
          type: string
        lastChecked:
          format: date-time
          type: string
        violationCount:
          format: int64
          type: integer
        scanStatus:
          type: boolean
        severityId:
          type: string
      title: AssetsWithViolations
      type: object
    AssetsWithViolationsResponse:
      example:
        totalCount: 0
        items:
        - severity: severity
          serialNumber: serialNumber
          violationCount: 6
          softwareType: softwareType
          assetId: assetId
          ipAddress: ipAddress
          assetName: assetName
          scanStatus: true
          softwareRelease: softwareRelease
          severityId: severityId
          lastChecked: 2000-01-23T04:56:07.000+00:00
        - severity: severity
          serialNumber: serialNumber
          violationCount: 6
          softwareType: softwareType
          assetId: assetId
          ipAddress: ipAddress
          assetName: assetName
          scanStatus: true
          softwareRelease: softwareRelease
          severityId: severityId
          lastChecked: 2000-01-23T04:56:07.000+00:00
      properties:
        totalCount:
          description: total Number of violations
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/AssetsWithViolations'
          type: array
      title: AssetsWithViolationsResponse
      type: object
    AssetViolation:
      example:
        severity: severity
        policyDescription: policyDescription
        regulatoryType: regulatoryType
        ruleTitle: ruleTitle
        suggestion: suggestion
        violationAge: 6
        ruleDescription: ruleDescription
        violationMessage: violationMessage
      properties:
        severity:
          type: string
        regulatoryType:
          type: string
        violationMessage:
          type: string
        violationAge:
          format: int64
          type: integer
        suggestion:
          type: string
        policyDescription:
          type: string
        ruleTitle:
          type: string
        ruleDescription:
          type: string
      title: AssetViolation
      type: object
    AssetViolationsResponse:
      example:
        totalCount: 0
        items:
        - severity: severity
          policyDescription: policyDescription
          regulatoryType: regulatoryType
          ruleTitle: ruleTitle
          suggestion: suggestion
          violationAge: 6
          ruleDescription: ruleDescription
          violationMessage: violationMessage
        - severity: severity
          policyDescription: policyDescription
          regulatoryType: regulatoryType
          ruleTitle: ruleTitle
          suggestion: suggestion
          violationAge: 6
          ruleDescription: ruleDescription
          violationMessage: violationMessage
      properties:
        totalCount:
          description: total Number of assets with Violations
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/AssetViolation'
          type: array
      title: AssetViolationsResponse
      type: object
    optInResponse:
      example:
        hasQualifiedAssets: hasQualifiedAssets
        status: status
      properties:
        status:
          type: string
        hasQualifiedAssets:
          type: string
      title: optInResponse
      type: object
    ErrorResponse:
      properties:
        code:
          format: int64
          type: integer
        message:
          type: string
        description:
          type: string
      type: object
  securitySchemes:
    OauthSecurity:
      description: These API required OAuth 2 client credentials grant type Bearer
        token
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://cloudsso.cisco.com/as/token.oauth2?
      type: oauth2
      x-kong-security-enable: false

