openapi: 3.0.0
info:
  contact:
    email: developer-support-pxcloud@cisco.com
    name: API Support
    url: https://cisco.com
  description: PX Cloud APIs for the Partners
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://cisco.com
  title: CX Partner Portal APIs
  version: "1.0"
servers:
- description: US Prod Environment
  url: https://api-cx.cisco.com/px
  x-external-backend:
    serviceType: ExternalName
    serviceProtocol: https
    servicePort: 443
    externalName: api-cx.cisco.com
    basePath: /px
tags:
- description: Insights-Faults-APIs
  name: Faults
paths:
  /v1/customers/{customerId}/insights/faults:
    get:
      deprecated: false
      description: Returns fault information for the customerId provided.
      operationId: getFaultsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: "The number of days to retrieve fault data for. This value can\
          \ be 1, 7, 15, 30. The default is 1."
        explode: true
        in: query
        name: days
        required: false
        schema:
          default: 1
          format: int32
          maximum: 30
          minimum: 1
          type: integer
        style: form
      - description: The number of items to skip before starting to collect the result
          set. The default value is 1.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          minimum: 1
          type: integer
        style: form
      - description: The maximum number of items to return
        explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaultsResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Faults details
      tags:
      - Faults
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/faults/{faultId}/summary:
    get:
      deprecated: false
      description: Returns detailed information for a fault based on the fault signatureId
        and customerId provided
      operationId: getFaultsSummaryUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: Unique identifier used in CX Cloud to identify the fault
        explode: false
        in: path
        name: faultId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaultsSummaryResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Fault summary
      tags:
      - Faults
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/faults/{faultId}/affectedAssets:
    get:
      deprecated: false
      description: "Returns information about the customer assets affected by the\
        \ fault, based on the fault signatureId and customerId provided"
      operationId: getAffectedAssetsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: Unique identifier used in CX Cloud to identify the fault
        explode: false
        in: path
        name: faultId
        required: true
        schema:
          type: integer
        style: simple
      - description: "The number of days to retrieve fault data for. This value can\
          \ be 1, 7, 15, 30. The default is 1."
        explode: true
        in: query
        name: days
        required: false
        schema:
          default: 1
          format: int32
          maximum: 30
          minimum: 1
          type: integer
        style: form
      - description: The number of items to skip before starting to collect the result
          set. The default value is 1.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          minimum: 1
          type: integer
        style: form
      - description: The maximum number of items to return.
        explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AffectedAssetsResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Affected Assets
      tags:
      - Faults
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/faults/{faultId}/affectedAssets/{assetName}/faultHistory:
    get:
      deprecated: false
      description: "Returns information about the occurrences of a fault on an asset\
        \ based on the fault signatureId, asset name, and customerId provided"
      operationId: getAffectedAssetsDetailsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: Unique identifier used in CX Cloud to identify the fault
        explode: false
        in: path
        name: faultId
        required: true
        schema:
          type: integer
        style: simple
      - description: Unique asset name
        explode: false
        in: path
        name: assetName
        required: true
        schema:
          type: string
        style: simple
      - description: "The number of days to retrieve fault data for. This value can\
          \ be 1, 7, 15, 30. The default is 1."
        explode: true
        in: query
        name: days
        required: false
        schema:
          default: 1
          format: int32
          maximum: 30
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetsFaultHistoryResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Assets Fault History
      tags:
      - Faults
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
components:
  schemas:
    FaultsResponse:
      example:
        totalCount: 0
        items:
        - severity: severity
          openCases: 1
          condition: condition
          lastOccurence: 2000-01-23T04:56:07.000+00:00
          affectedAssets: affectedAssets
          faultId: 6
          occurences: 5
          title: title
          category: category
          ignoredAssets: 5
          caseAutomation: enabled
        - severity: severity
          openCases: 1
          condition: condition
          lastOccurence: 2000-01-23T04:56:07.000+00:00
          affectedAssets: affectedAssets
          faultId: 6
          occurences: 5
          title: title
          category: category
          ignoredAssets: 5
          caseAutomation: enabled
      properties:
        totalCount:
          description: Number of faults returned for the customer
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/Faults'
          type: array
      title: FaultsResponse
      type: object
    Faults:
      example:
        severity: severity
        openCases: 1
        condition: condition
        lastOccurence: 2000-01-23T04:56:07.000+00:00
        affectedAssets: affectedAssets
        faultId: 6
        occurences: 5
        title: title
        category: category
        ignoredAssets: 5
        caseAutomation: enabled
      properties:
        severity:
          description: Severity value assigned by CX Cloud
          type: string
        title:
          description: Title of the fault
          type: string
        lastOccurence:
          description: Date the fault last occurred
          format: date-time
          type: string
        condition:
          description: "The facility, condition severity, and mnemonic portion of\
            \ the fault message"
          type: string
        caseAutomation:
          description: Indicates whether support case automation has been enabled
            for the fault
          enum:
          - enabled
          - disabled
          type: string
        faultId:
          description: Unique identifier used in CX Cloud to identify the fault
          type: integer
        category:
          description: "The category assigned to the fault by CX Cloud, for example\
            \ System, CPU-Memory, Services, and Environment"
          type: string
        openCases:
          description: Number of Cisco support cases automatically created for the
            fault
          type: integer
        affectedAssets:
          description: Number of assets affected by the fault
          type: string
        occurences:
          description: Number of times the fault occurred
          type: integer
        ignoredAssets:
          description: Number of assets the fault is ignored for
          type: integer
      title: Faults
      type: object
    FaultsSummaryResponse:
      example:
        items:
        - severity: severity
          condition: condition
          suggestion: suggestion
          impact: impact
          description: description
          supportedProductSeries: supportedProductSeries
          title: title
          category: category
        - severity: severity
          condition: condition
          suggestion: suggestion
          impact: impact
          description: description
          supportedProductSeries: supportedProductSeries
          title: title
          category: category
      properties:
        items:
          items:
            $ref: '#/components/schemas/FaultsSummary'
          type: array
      title: FaultsSummaryResponse
      type: object
    FaultsSummary:
      example:
        severity: severity
        condition: condition
        suggestion: suggestion
        impact: impact
        description: description
        supportedProductSeries: supportedProductSeries
        title: title
        category: category
      properties:
        title:
          description: Title of the fault
          type: string
        suggestion:
          description: Suggestion provided by CX Cloud to help address the fault
          type: string
        description:
          description: Detailed description of the fault
          type: string
        condition:
          description: "The facility, condition severity, and mnemonic portion of\
            \ the fault message"
          type: string
        category:
          description: "The category assigned to the fault by CX Cloud, such as System,\
            \ CPU-Memory, Services, and Environment"
          type: string
        supportedProductSeries:
          description: Cisco product families the fault applies to
          type: string
        impact:
          description: The possible effect the fault has on the assets and network
          type: string
        severity:
          description: Severity value assigned by CX Cloud
          type: string
      title: FaultsSummary
      type: object
    AffectedAssetsResponse:
      example:
        totalCount: 0
        items:
        - occurrences: 6
          caseAction: caseAction
          serialNumber: serialNumber
          productId: productId
          caseNumber: caseNumber
          firstOccurrence: 2000-01-23T04:56:07.000+00:00
          lastOccurrence: 2000-01-23T04:56:07.000+00:00
          faultId: 1
          assetName: assetName
        - occurrences: 6
          caseAction: caseAction
          serialNumber: serialNumber
          productId: productId
          caseNumber: caseNumber
          firstOccurrence: 2000-01-23T04:56:07.000+00:00
          lastOccurrence: 2000-01-23T04:56:07.000+00:00
          faultId: 1
          assetName: assetName
      properties:
        totalCount:
          description: Number of assets affected by the fault
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/AffectedAssets'
          type: array
      title: AffectedAssetsResponse
      type: object
    AffectedAssets:
      example:
        occurrences: 6
        caseAction: caseAction
        serialNumber: serialNumber
        productId: productId
        caseNumber: caseNumber
        firstOccurrence: 2000-01-23T04:56:07.000+00:00
        lastOccurrence: 2000-01-23T04:56:07.000+00:00
        faultId: 1
        assetName: assetName
      properties:
        assetName:
          description: Unique asset name
          type: string
        productId:
          description: Cisco product number of the asset
          type: string
        caseNumber:
          description: "If case automation is enabled, this is the Cisco support case\
            \ number created"
          type: string
        caseAction:
          description: "If case automation is enabled, this is the status of the Cisco\
            \ support case request submitted by CX Cloud for the asset"
          type: string
        occurrences:
          description: Number of times the fault occurred on the asset
          type: integer
        firstOccurrence:
          description: Date the fault first occurred on the asset
          format: date-time
          type: string
        lastOccurrence:
          description: Date the fault last occurred on the asset
          format: date-time
          type: string
        faultId:
          description: Unique identifier used in CX Cloud to identify the fault
          type: integer
        serialNumber:
          description: Unique Cisco serial number of the asset
          type: string
      title: AffectedAssets
      type: object
    AssetsFaultHistoryResponse:
      example:
        totalCount: 0
        items:
        - lastOccurrence: 2000-01-23T04:56:07.000+00:00
          failureMessage: failureMessage
          status: status
        - lastOccurrence: 2000-01-23T04:56:07.000+00:00
          failureMessage: failureMessage
          status: status
      properties:
        totalCount:
          description: Number of fault occurrences returned
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/AssetsFaultHistory'
          type: array
      title: AssetsFaultHistoryResponse
      type: object
    AssetsFaultHistory:
      example:
        lastOccurrence: 2000-01-23T04:56:07.000+00:00
        failureMessage: failureMessage
        status: status
      properties:
        status:
          description: "If case automation is enabled when the fault occurs, this\
            \ returns the status of the Cisco support case request submitted by CX\
            \ Cloud. If case automation is not enabled, this returns \"Fault Occurred\"\
            ."
          type: string
        failureMessage:
          description: Error message returned when the value of the status attribute
            is "Failed"
          type: string
        lastOccurrence:
          description: Date the fault occurred
          format: date-time
          type: string
      title: AssetsFaultHistory
      type: object
    ErrorResponse:
      properties:
        code:
          format: int64
          type: integer
        message:
          type: string
        description:
          type: string
      type: object
  securitySchemes:
    OauthSecurity:
      description: These API required OAuth 2 client credentials grant type Bearer
        token
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://cloudsso.cisco.com/as/token.oauth2?
      type: oauth2
      x-kong-security-enable: false

