openapi: 3.0.0
info:
  contact:
    email: developer-support-pxcloud@cisco.com
    name: API Support
    url: https://cisco.com
  description: CX Partner Portal APIs for the Partners
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://cisco.com
  title: CX Partner Portal APIs
  version: "1.0"
servers:
- description: US Prod Environment
  url: https://api-cx.cisco.com/px
  x-external-backend:
    serviceType: ExternalName
    serviceProtocol: https
    servicePort: 443
    externalName: api-cx.cisco.com
    basePath: /px
tags:
- description: Insights-Crash Risk-APIs
  name: Crash Risk
paths:
  /v1/customers/{customerId}/insights/crashRisk/assets:
    get:
      description: "This API provides details of the devices that have a probability\
        \ of crash with crash score rating as High, Medium and Low. Default sorting\
        \ is End date"
      operationId: crashRiskAssetsUsingGet
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrashRiskDevices'
          description: Ok
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden error
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: "Get devices which are at risk of crash owned by a customer, sorted\
        \ by risk score in descending order by default"
      tags:
      - Crash Risk
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-access-permission: right_to_view_crash_risk_and_crashed_score_cards_and_corresponding_grids
      x-accepts: application/json
  /v1/customers/{customerId}/insights/crashRisk/assets/{assetIdBase64}/riskFactors:
    get:
      description: This API provides list of risk factors that contribute to the high
        risk score. Default sorting is factorWeight
      operationId: assetRiskFactorsUsingGet
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: base64 encoded value of the assetId
        explode: false
        in: path
        name: assetIdBase64
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceRiskFactors'
          description: Ok
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden error
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Get risk factors of a device
      tags:
      - Crash Risk
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-access-permission: right_to_view_similar_and_compare_devices_from_crash_risk_grid
      x-accepts: application/json
  /v1/customers/{customerId}/insights/crashRisk/assets/{assetIdBase64}/similarAssets:
    get:
      description: "This API provides details of other devices in the network that\
        \ are similar to the current device pre in terms of features , prodict familiy\
        \ and hardware. Default sort is similarityScore"
      operationId: similarAssetsUsingGet
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: base64 encoded value of the assetId
        explode: false
        in: path
        name: assetIdBase64
        required: true
        schema:
          type: string
        style: simple
      - description: "should be one of the following values features,fingerprint,softwares_features"
        explode: true
        in: query
        name: similarityCriteria
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 1
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: max
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimilarDevices'
          description: Ok
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden error
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Get similar assets based on the similarity score
      tags:
      - Crash Risk
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-access-permission: right_to_view_similar_and_compare_devices_from_crash_risk_grid
      x-accepts: application/json
  /v1/customers/{customerId}/insights/crashRisk/assetsCrashed:
    get:
      deprecated: false
      description: "This API provides the list of devices with details (i.e. Asset,\
        \ Product Id, Product Family, Software Version, Crash Count, First Occurrence\
        \ and Last Occurrence) by customer Id that have crashed in the last 1d,7d,15d,90d\
        \ based on the filter input. Default sort is by lastCrashDate"
      operationId: assetsCrashedUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: customerId
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: timePeriod
        explode: true
        in: query
        name: timePeriod
        required: false
        schema:
          default: "1"
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryCrashDetails'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Get the list of crashed devices for last given time period
      tags:
      - Crash Risk
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-access-permission: right_to_view_details_from_crashed_devices_grid
      x-accepts: application/json
  /v1/customers/{customerId}/insights/crashRisk/asset/{assetIdBase64}/crashHistory:
    get:
      deprecated: false
      description: Details of the number of times the device crashed in the last 365
        days with reset reason. Default sort is by timeStamp
      operationId: crashHistoryUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: customerId
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: base64 encoded value of the assetId
        explode: false
        in: path
        name: assetIdBase64
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCrashDetail'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: "Get the device crash-detail - Asset 360(time stamp, reset reason)"
      tags:
      - Crash Risk
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-access-permission: right_to_view_details_from_crashed_devices_grid
      x-accepts: application/json
components:
  schemas:
    CrashRiskDevices:
      example:
        devices:
        - productFamily: productFamily
          serialNumber: serialNumber
          productId: productId
          softwareType: softwareType
          endDate: endDate
          assetId: assetId
          ipAddress: ipAddress
          assetName: assetName
          risk: risk
          softwareRelease: softwareRelease
        - productFamily: productFamily
          serialNumber: serialNumber
          productId: productId
          softwareType: softwareType
          endDate: endDate
          assetId: assetId
          ipAddress: ipAddress
          assetName: assetName
          risk: risk
          softwareRelease: softwareRelease
        crashPredicted: true
        totalCount: 0
      properties:
        totalCount:
          format: int64
          type: integer
        crashPredicted:
          type: boolean
        devices:
          items:
            $ref: '#/components/schemas/CrashRiskDevice'
          type: array
      type: object
    DeviceRiskFactorsResponse:
      properties:
        totalCount:
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/DeviceRiskFactors'
          type: array
      title: softwareGroupResponse
      type: object
    DeviceRiskFactors:
      example:
        factorType: factorType
        factor: factor
      properties:
        factor:
          type: string
        factorType:
          type: string
      title: DeviceRiskFactors
      type: object
    SimilarDevices:
      example:
        crashPredicted: true
        totalCount: 0
        items:
        - productFamily: productFamily
          serialNumber: serialNumber
          productId: productId
          softwareType: softwareType
          assetId: assetId
          assetName: assetName
          risk: risk
          softwareRelease: softwareRelease
          similarityScore: 6.027456183070403
        - productFamily: productFamily
          serialNumber: serialNumber
          productId: productId
          softwareType: softwareType
          assetId: assetId
          assetName: assetName
          risk: risk
          softwareRelease: softwareRelease
          similarityScore: 6.027456183070403
      properties:
        totalCount:
          format: int32
          type: integer
        crashPredicted:
          type: boolean
        items:
          items:
            $ref: '#/components/schemas/SimilarDeviceData'
          type: array
      type: object
    SimilarDeviceData:
      example:
        productFamily: productFamily
        serialNumber: serialNumber
        productId: productId
        softwareType: softwareType
        assetId: assetId
        assetName: assetName
        risk: risk
        softwareRelease: softwareRelease
        similarityScore: 6.027456183070403
      properties:
        assetId:
          type: string
        assetName:
          type: string
        productFamily:
          type: string
        productId:
          type: string
        softwareRelease:
          type: string
        softwareType:
          type: string
        risk:
          type: string
        serialNumber:
          type: string
        similarityScore:
          format: double
          type: number
      type: object
    CrashRiskDevice:
      example:
        productFamily: productFamily
        serialNumber: serialNumber
        productId: productId
        softwareType: softwareType
        endDate: endDate
        assetId: assetId
        ipAddress: ipAddress
        assetName: assetName
        risk: risk
        softwareRelease: softwareRelease
      properties:
        assetId:
          type: string
        assetName:
          type: string
        productId:
          type: string
        productFamily:
          type: string
        ipAddress:
          type: string
        softwareRelease:
          type: string
        softwareType:
          type: string
        serialNumber:
          type: string
        risk:
          type: string
        endDate:
          type: string
      type: object
    InventoryCrashDetails:
      example:
        items:
        - productFamily: productFamily
          crashCount: 0
          lastCrashDate: 2000-01-23T04:56:07.000+00:00
          serialNumber: serialNumber
          productId: productId
          softwareType: softwareType
          assetId: assetId
          firstCrashDate: 2000-01-23T04:56:07.000+00:00
          ipAddress: ipAddress
          assetName: assetName
          softwareRelease: softwareRelease
        - productFamily: productFamily
          crashCount: 0
          lastCrashDate: 2000-01-23T04:56:07.000+00:00
          serialNumber: serialNumber
          productId: productId
          softwareType: softwareType
          assetId: assetId
          firstCrashDate: 2000-01-23T04:56:07.000+00:00
          ipAddress: ipAddress
          assetName: assetName
          softwareRelease: softwareRelease
      properties:
        items:
          items:
            $ref: '#/components/schemas/DeviceDetail'
          type: array
      title: InventoryCrashDetails
      type: object
    DeviceDetail:
      example:
        productFamily: productFamily
        crashCount: 0
        lastCrashDate: 2000-01-23T04:56:07.000+00:00
        serialNumber: serialNumber
        productId: productId
        softwareType: softwareType
        assetId: assetId
        firstCrashDate: 2000-01-23T04:56:07.000+00:00
        ipAddress: ipAddress
        assetName: assetName
        softwareRelease: softwareRelease
      properties:
        crashCount:
          format: int64
          type: integer
        firstCrashDate:
          format: date-time
          type: string
        ipAddress:
          type: string
        lastCrashDate:
          format: date-time
          type: string
        assetId:
          type: string
        assetName:
          type: string
        productFamily:
          type: string
        productId:
          type: string
        serialNumber:
          type: string
        softwareType:
          type: string
        softwareRelease:
          type: string
      title: DeviceDetail
      type: object
    DeviceCrashDetail:
      example:
        items:
        - resetReason: resetReason
          timeStamp: 2000-01-23T04:56:07.000+00:00
        - resetReason: resetReason
          timeStamp: 2000-01-23T04:56:07.000+00:00
      properties:
        items:
          items:
            $ref: '#/components/schemas/Crash'
          type: array
      title: DeviceCrashDetail
      type: object
    Crash:
      example:
        resetReason: resetReason
        timeStamp: 2000-01-23T04:56:07.000+00:00
      properties:
        resetReason:
          type: string
        timeStamp:
          format: date-time
          type: string
      title: Crash
      type: object
    ErrorResponse:
      properties:
        code:
          format: int64
          type: integer
        message:
          type: string
        description:
          type: string
      type: object
  securitySchemes:
    OauthSecurity:
      description: These API required OAuth 2 client credentials grant type Bearer
        token
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://cloudsso.cisco.com/as/token.oauth2?
      type: oauth2
      x-kong-security-enable: false

