openapi: 3.0.0
info:
  contact:
    email: developer-support-pxcloud@cisco.com
    name: API Support
    url: https://cisco.com
  description: PX Cloud APIs for the Partners
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://cisco.com
  title: CX Partner Portal APIs
  version: "1.0"
servers:
- description: US Prod Environment
  url: https://api-cx.cisco.com/px
  x-external-backend:
    serviceType: ExternalName
    serviceProtocol: https
    servicePort: 443
    externalName: api-cx.cisco.com
    basePath: /px
tags:
- description: Insights-Software Groups-APIs
  name: Insights
paths:
  /v1/customers/{customerId}/insights/software/softwareGroups:
    get:
      deprecated: false
      description: Returns Software Group information for the customerId provided
      operationId: getSoftwareGroupsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: The number of items to skip before starting to collect the result
          set. The default value is 1.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: The maximum number of items to return
        explode: true
        in: query
        name: max
        required: false
        schema:
          default: 50
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/softwareGroupResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Software Group information
      tags:
      - Insights
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/software/softwareGroups/{softwareGroupName}/suggestions:
    get:
      deprecated: false
      description: "Returns Software Group suggestions, including detailed information\
        \ about Cisco software release recommendations and current Cisco software\
        \ releases running on assets in the Software Group"
      operationId: getSoftwareGroupSuggestionsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: "Name of the Software Group, which is based on the Cisco product\
          \ ID of the assets in the Software Group"
        explode: false
        in: path
        name: softwareGroupName
        required: true
        schema:
          type: string
        style: simple
      - description: UUID of the Cisco network management system that manages the
          assets in the Software Group
        explode: true
        in: query
        name: sourceSystemId
        required: true
        schema:
          type: string
        style: form
      - description: Cisco software type running on the assets in the Software Group
        explode: true
        in: query
        name: softwareType
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/softwareGroupSuggestions'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Software Group suggestions
      tags:
      - Insights
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
  /v1/customers/{customerId}/insights/software/softwareGroups/{softwareGroupId}/assets:
    get:
      description: Returns information about assets in the Software Group based on
        the customerId and softwareGroupId provided
      operationId: getSoftwareGroupAssetsUsingGET
      parameters:
      - explode: true
        in: query
        name: successTrackId
        required: true
        schema:
          type: string
        style: form
      - description: Unique identifier of the customer
        explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: string
        style: simple
      - description: Unique identifier used in CX Cloud to identify the Software Group
        explode: false
        in: path
        name: softwareGroupId
        required: true
        schema:
          type: string
        style: simple
      - description: The number of items to skip before starting to collect the result
          set. The default value is 1.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: The maximum number of items to return
        explode: true
        in: query
        name: max
        required: false
        schema:
          default: 50
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetResponse'
          description: OK
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
          headers:
            Date:
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
      summary: Asset information in the Software Group
      tags:
      - Insights
      x-kong-rate-limiting-cisco:
        limit_by: header
        header_name: Authorization
        second: 3
      x-accepts: application/json
components:
  schemas:
    softwareGroupResponse:
      example:
        totalCount: 0
        items:
        - sourceId: sourceId
          productFamily: productFamily
          currentReleases: currentReleases
          riskLevel: riskLevel
          softwareGroupId: softwareGroupId
          softwareType: softwareType
          sourceSystemId: sourceSystemId
          selectedRelease: selectedRelease
          suggestions: suggestions
          assetCount: 6
          softwareGroupName: softwareGroupName
        - sourceId: sourceId
          productFamily: productFamily
          currentReleases: currentReleases
          riskLevel: riskLevel
          softwareGroupId: softwareGroupId
          softwareType: softwareType
          sourceSystemId: sourceSystemId
          selectedRelease: selectedRelease
          suggestions: suggestions
          assetCount: 6
          softwareGroupName: softwareGroupName
      properties:
        totalCount:
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/softwareGroup'
          type: array
      title: softwareGroupResponse
      type: object
    softwareGroup:
      example:
        sourceId: sourceId
        productFamily: productFamily
        currentReleases: currentReleases
        riskLevel: riskLevel
        softwareGroupId: softwareGroupId
        softwareType: softwareType
        sourceSystemId: sourceSystemId
        selectedRelease: selectedRelease
        suggestions: suggestions
        assetCount: 6
        softwareGroupName: softwareGroupName
      properties:
        assetCount:
          description: Number of assets in the Software Group
          format: int32
          type: integer
        sourceId:
          description: IP address of the Cisco network management system that manages
            the assets in the Software Group
          type: string
        sourceSystemId:
          description: Unique identifier of the Cisco network management system that
            manages the assets in the Software Group
          type: string
        selectedRelease:
          description: The suggested Cisco software release the customer selected
            to use for the next software update on the assets in the Software Group
          type: string
        productFamily:
          description: "Cisco product family of the assets in the Software Group,\
            \ for example Cisco Catalyst 9300 Series Switches"
          type: string
        softwareGroupName:
          description: Software Group name based on the Cisco product ID of the assets
            in the Software Group
          type: string
        softwareGroupId:
          description: Unique identifier used in CX Cloud to identify the Software
            Group
          type: string
        suggestions:
          description: Indicates whether Cisco software release suggestions are available
            for the Software Group
          type: string
        riskLevel:
          description: "Risk level of the Software Group based on the risk scores\
            \ of the current Cisco software releases in the Software Group. The risk\
            \ level can be High, Medium, or Low."
          type: string
        softwareType:
          description: "Cisco software type running on the assets in the Software\
            \ Group, for example IOS-XE"
          type: string
        currentReleases:
          description: The Cisco software releases running on assets in the Software
            Group
          type: string
      title: softwareGroup
      type: object
    softwareGroupSuggestions:
      example:
        sourceId: sourceId
        suggestionSummaries:
        - advisoriesSeverity:
          - newOpen:
              high: 1
              low: 4
              medium: 5
            open:
              high: 9
              low: 9
              medium: 6
            resolved:
              high: 1
              low: 6
              medium: 7
          - newOpen:
              high: 1
              low: 4
              medium: 5
            open:
              high: 9
              low: 9
              medium: 6
            resolved:
              high: 1
              low: 6
              medium: 7
          expectedSoftwareGroupRiskCategory: expectedSoftwareGroupRiskCategory
          releaseDate: 2000-01-23T04:56:07.000+00:00
          suggestionId: 5.637376656633329
          release: release
          fieldNoticeSeverity:
          - newOpen:
              medium: 9
            open:
              medium: 6
            resolved:
              medium: 8
          - newOpen:
              medium: 9
            open:
              medium: 6
            resolved:
              medium: 8
          name: name
          releaseNotesUrl: releaseNotesUrl
          expectedSoftwareGroupRisk: 5.962133916683182
          bugSeverity:
          - newOpen:
              high: 3
              low: 2
              medium: 4
            open:
              high: 7
              low: 1
              medium: 1
            resolved:
              high: 2
              low: 7
              medium: 9
          - newOpen:
              high: 3
              low: 2
              medium: 4
            open:
              high: 7
              low: 1
              medium: 1
            resolved:
              high: 2
              low: 7
              medium: 9
        - advisoriesSeverity:
          - newOpen:
              high: 1
              low: 4
              medium: 5
            open:
              high: 9
              low: 9
              medium: 6
            resolved:
              high: 1
              low: 6
              medium: 7
          - newOpen:
              high: 1
              low: 4
              medium: 5
            open:
              high: 9
              low: 9
              medium: 6
            resolved:
              high: 1
              low: 6
              medium: 7
          expectedSoftwareGroupRiskCategory: expectedSoftwareGroupRiskCategory
          releaseDate: 2000-01-23T04:56:07.000+00:00
          suggestionId: 5.637376656633329
          release: release
          fieldNoticeSeverity:
          - newOpen:
              medium: 9
            open:
              medium: 6
            resolved:
              medium: 8
          - newOpen:
              medium: 9
            open:
              medium: 6
            resolved:
              medium: 8
          name: name
          releaseNotesUrl: releaseNotesUrl
          expectedSoftwareGroupRisk: 5.962133916683182
          bugSeverity:
          - newOpen:
              high: 3
              low: 2
              medium: 4
            open:
              high: 7
              low: 1
              medium: 1
            resolved:
              high: 2
              low: 7
              medium: 9
          - newOpen:
              high: 3
              low: 2
              medium: 4
            open:
              high: 7
              low: 1
              medium: 1
            resolved:
              high: 2
              low: 7
              medium: 9
        basicSuggestedDate: 2000-01-23
        softwareGroupRiskTrend:
        - date: 2000-01-23
          riskCategory: riskCategory
          changeFromPrev: 6.027456183070403
          changeMessage: changeMessage
          name: name
          riskScore: 1.4658129805029452
        - date: 2000-01-23
          riskCategory: riskCategory
          changeFromPrev: 6.027456183070403
          changeMessage: changeMessage
          name: name
          riskScore: 1.4658129805029452
        releaseSummary:
        - releaseDate: 2000-01-23
          release: release
          name: name
          error: error
        - releaseDate: 2000-01-23
          release: release
          name: name
          error: error
        suggestionUpdatedDate: 2000-01-23
        suggestionsInterval: 0
        selectedRelease: selectedRelease
        suggestionSelectedDate: 2000-01-23
        softwareGroupName: softwareGroupName
      properties:
        sourceId:
          description: IP address of the Cisco network management system that manages
            the assets in the Software Group.
          type: string
        basicSuggestedDate:
          description: Date the basic suggestions were updated for the Software Group
          format: date
          type: string
        softwareGroupName:
          description: Name of the Software Group whose data is being retrieved
          type: string
        suggestionUpdatedDate:
          description: Date the machine learning suggestions were updated for the
            Software Group
          format: date
          type: string
        suggestionsInterval:
          description: "How often, in months, Cisco software release suggestions will\
            \ be provided. The customer can configure this value in CX Cloud."
          format: int32
          type: integer
        selectedRelease:
          description: The suggested Cisco software release the customer has selected
            to use the next time a software update is performed on the assets in the
            Software Group
          type: string
        suggestionSelectedDate:
          description: Date the customer selected a suggested Cisco software release
            in CX Cloud
          format: date
          type: string
        softwareGroupRiskTrend:
          description: List of weekly risk scores for the current Cisco software releases
            calculated over a period of time
          items:
            $ref: '#/components/schemas/SoftwareGroupRisk'
          type: array
        suggestionSummaries:
          description: "Information about the Cisco software releases running on,\
            \ and suggested for, the assets in the Software Group"
          items:
            $ref: '#/components/schemas/SuggestionSummary'
          type: array
        releaseSummary:
          description: List of the following Cisco software releases for the Software
            Group - • Latest release available from Cisco Software Central • Suggested
            releases • Cisco DNA Center golden release • Cisco DNA Center Compatibility
            Matrix minimum release
          items:
            $ref: '#/components/schemas/ReleaseSummary'
          type: array
      title: softwareGroupSuggestions
      type: object
    SoftwareGroupRisk:
      example:
        date: 2000-01-23
        riskCategory: riskCategory
        changeFromPrev: 6.027456183070403
        changeMessage: changeMessage
        name: name
        riskScore: 1.4658129805029452
      properties:
        changeFromPrev:
          description: The percentage the risk score has changed from the previous
            week
          format: double
          type: number
        changeMessage:
          description: Label for the Risk Score Trend graph in CX Cloud that is displayed
            with the risk score value
          type: string
        name:
          description: Value for the Risk Score Trend graph in CX Cloud to identify
            the data point type
          type: string
        riskCategory:
          description: "Risk level of the Cisco software release based on its risk\
            \ score. The risk level can be High, Medium, or Low."
          type: string
        date:
          description: Date the weekly risk score was calculated
          format: date
          type: string
        riskScore:
          description: Risk score of the Cisco software release for the softwareGroupRiskTrend
            date
          format: double
          type: number
      title: SoftwareGroupRisk
      type: object
    SuggestionSummary:
      example:
        advisoriesSeverity:
        - newOpen:
            high: 1
            low: 4
            medium: 5
          open:
            high: 9
            low: 9
            medium: 6
          resolved:
            high: 1
            low: 6
            medium: 7
        - newOpen:
            high: 1
            low: 4
            medium: 5
          open:
            high: 9
            low: 9
            medium: 6
          resolved:
            high: 1
            low: 6
            medium: 7
        expectedSoftwareGroupRiskCategory: expectedSoftwareGroupRiskCategory
        releaseDate: 2000-01-23T04:56:07.000+00:00
        suggestionId: 5.637376656633329
        release: release
        fieldNoticeSeverity:
        - newOpen:
            medium: 9
          open:
            medium: 6
          resolved:
            medium: 8
        - newOpen:
            medium: 9
          open:
            medium: 6
          resolved:
            medium: 8
        name: name
        releaseNotesUrl: releaseNotesUrl
        expectedSoftwareGroupRisk: 5.962133916683182
        bugSeverity:
        - newOpen:
            high: 3
            low: 2
            medium: 4
          open:
            high: 7
            low: 1
            medium: 1
          resolved:
            high: 2
            low: 7
            medium: 9
        - newOpen:
            high: 3
            low: 2
            medium: 4
          open:
            high: 7
            low: 1
            medium: 1
          resolved:
            high: 2
            low: 7
            medium: 9
      properties:
        expectedSoftwareGroupRisk:
          description: "Current risk score of the Cisco software release, which is\
            \ the level of exposure the software release has to bugs, security advisories,\
            \ and field notices. The risk score is used to make software suggestions\
            \ intended to minimize risk for assets in the Software Group."
          format: double
          type: number
        expectedSoftwareGroupRiskCategory:
          description: "Risk level of the Cisco software release based on its risk\
            \ score. The risk level can be High, Medium, or Low."
          type: string
        suggestionId:
          description: Unique identifier of the suggestion
          type: number
        name:
          description: Value that indicates whether the Cisco software release is
            a current release or one of the suggested release options
          type: string
        releaseDate:
          description: Date the Cisco software image was released
          format: date-time
          type: string
        release:
          description: Release of the Cisco software
          type: string
        releaseNotesUrl:
          description: Public URL for the release notes of the Cisco software release
          type: string
        bugSeverity:
          description: "Number of bugs the Cisco software release is exposed to, and\
            \ for suggested releases, the number of bugs the suggested release addresses"
          items:
            $ref: '#/components/schemas/SuggestionSummary_bugSeverity_inner'
          type: array
        advisoriesSeverity:
          description: Number of security advisories the current Cisco software releases
            are exposed to that are addressed by the suggested release
          items:
            $ref: '#/components/schemas/SuggestionSummary_advisoriesSeverity_inner'
          type: array
        fieldNoticeSeverity:
          description: Number of field notices the current Cisco software releases
            are exposed to that are addressed by the suggested release
          items:
            $ref: '#/components/schemas/SuggestionSummary_fieldNoticeSeverity_inner'
          type: array
      title: SuggestionSummary
      type: object
    ReleaseSummary:
      example:
        releaseDate: 2000-01-23
        release: release
        name: name
        error: error
      properties:
        error:
          type: string
        name:
          type: string
        releaseDate:
          format: date
          type: string
        release:
          type: string
      title: Suggestion
      type: object
    AssetResponse:
      example:
        totalCount: 0
        items:
        - deploymentStatus: deploymentStatus
          currentRelease: currentRelease
          releaseDate: 2000-01-23
          softwareType: softwareType
          ipAddress: ipAddress
          assetName: assetName
          selectedRelease: selectedRelease
          softwareGroupName: softwareGroupName
        - deploymentStatus: deploymentStatus
          currentRelease: currentRelease
          releaseDate: 2000-01-23
          softwareType: softwareType
          ipAddress: ipAddress
          assetName: assetName
          selectedRelease: selectedRelease
          softwareGroupName: softwareGroupName
      properties:
        totalCount:
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/Asset'
          type: array
      title: AssetResponse
      type: object
    Asset:
      example:
        deploymentStatus: deploymentStatus
        currentRelease: currentRelease
        releaseDate: 2000-01-23
        softwareType: softwareType
        ipAddress: ipAddress
        assetName: assetName
        selectedRelease: selectedRelease
        softwareGroupName: softwareGroupName
      properties:
        deploymentStatus:
          description: Value that indicates whether a suggested Cisco software release
            has been selected by the customer in CX Cloud to use for the next software
            update on the asset - • None- A suggested release has not been selected
            • Upgrade- A suggested release has been selected • Production- A suggested
            release is already running on the asset
          type: string
        assetName:
          description: Unique asset name
          type: string
        ipAddress:
          description: IP address assigned to the asset
          type: string
        selectedRelease:
          description: The suggested Cisco software release the customer selected
            to use for the next software update on the asset
          type: string
        releaseDate:
          description: Date the Cisco software image was released
          format: date
          type: string
        softwareGroupName:
          description: Name of the Software Group whose data is being retrieved. The
            Software Group name is based on the Cisco product ID of the assets in
            the Software Group.
          type: string
        softwareType:
          description: "Cisco software type running on the asset, for example IOS-XE"
          type: string
        currentRelease:
          description: Cisco software release running on the asset
          type: string
      title: Asset
      type: object
    ErrorResponse:
      properties:
        code:
          format: int64
          type: integer
        message:
          type: string
        description:
          type: string
      type: object
    SuggestionSummary_bugSeverity_inner_resolved:
      description: "Number of bugs the current Cisco software releases are exposed\
        \ to that are addressed by the suggested release, grouped by severity."
      example:
        high: 2
        low: 7
        medium: 9
      properties:
        high:
          description: Number of High severity bugs addressed by the suggested Cisco
            software release
          format: int64
          type: integer
        low:
          description: Number of Low severity bugs addressed by the suggested Cisco
            software release
          format: int64
          type: integer
        medium:
          description: Number of Medium severity bugs addressed by the suggested Cisco
            software release
          format: int64
          type: integer
      type: object
    SuggestionSummary_bugSeverity_inner_newOpen:
      description: "Number of new bugs the suggested Cisco software release is exposed\
        \ to compared to the current Cisco software releases, grouped by severity"
      example:
        high: 3
        low: 2
        medium: 4
      properties:
        high:
          description: Number of new High severity bugs the suggested Cisco software
            release is exposed to compared to the current Cisco software releases
          format: int64
          type: integer
        low:
          description: Number of new Low severity bugs the suggested Cisco software
            release is exposed to compared to the current Cisco software releases
          format: int64
          type: integer
        medium:
          description: Number of new Medium severity bugs the suggested Cisco software
            release is exposed to compared to the current Cisco software releases
          format: int64
          type: integer
      type: object
    SuggestionSummary_bugSeverity_inner_open:
      description: "Number of bugs the current Cisco software releases are exposed\
        \ to, grouped by severity"
      example:
        high: 7
        low: 1
        medium: 1
      properties:
        high:
          description: Number of High severity bugs the current Cisco software releases
            are exposed to
          format: int64
          type: integer
        low:
          description: Number of Low severity bugs the current Cisco software releases
            are exposed to
          format: int64
          type: integer
        medium:
          description: Number of Medium severity bugs the current Cisco software releases
            are exposed to
          format: int64
          type: integer
      type: object
    SuggestionSummary_bugSeverity_inner:
      example:
        newOpen:
          high: 3
          low: 2
          medium: 4
        open:
          high: 7
          low: 1
          medium: 1
        resolved:
          high: 2
          low: 7
          medium: 9
      properties:
        resolved:
          $ref: '#/components/schemas/SuggestionSummary_bugSeverity_inner_resolved'
        newOpen:
          $ref: '#/components/schemas/SuggestionSummary_bugSeverity_inner_newOpen'
        open:
          $ref: '#/components/schemas/SuggestionSummary_bugSeverity_inner_open'
      type: object
    SuggestionSummary_advisoriesSeverity_inner_resolved:
      description: "Number of security advisories the current Cisco software releases\
        \ are exposed to that are addressed by the suggested release, grouped by impact"
      example:
        high: 1
        low: 6
        medium: 7
      properties:
        high:
          description: Number of High impact security advisories addressed by the
            suggested Cisco software release
          format: int64
          type: integer
        low:
          description: Number of Low impact security advisories addressed by the suggested
            Cisco software release
          format: int64
          type: integer
        medium:
          description: Number of Medium impact security advisories addressed by the
            suggested Cisco software release
          format: int64
          type: integer
      type: object
    SuggestionSummary_advisoriesSeverity_inner_newOpen:
      description: Number of new security advisories the current Cisco software release
        are exposed to compared to the current Cisco software releases
      example:
        high: 1
        low: 4
        medium: 5
      properties:
        high:
          description: Number of new High impact security advisories
          format: int64
          type: integer
        low:
          description: Number of new Low impact security advisories
          format: int64
          type: integer
        medium:
          description: Number of new Medium impact security advisories
          format: int64
          type: integer
      type: object
    SuggestionSummary_advisoriesSeverity_inner_open:
      description: Number of security advisories the current Cisco software release
        are exposed to
      example:
        high: 9
        low: 9
        medium: 6
      properties:
        high:
          description: Number of High impact security advisories
          format: int64
          type: integer
        low:
          description: Number of Low impact security advisories
          format: int64
          type: integer
        medium:
          description: Number of Medium impact security advisories
          format: int64
          type: integer
      type: object
    SuggestionSummary_advisoriesSeverity_inner:
      example:
        newOpen:
          high: 1
          low: 4
          medium: 5
        open:
          high: 9
          low: 9
          medium: 6
        resolved:
          high: 1
          low: 6
          medium: 7
      properties:
        resolved:
          $ref: '#/components/schemas/SuggestionSummary_advisoriesSeverity_inner_resolved'
        newOpen:
          $ref: '#/components/schemas/SuggestionSummary_advisoriesSeverity_inner_newOpen'
        open:
          $ref: '#/components/schemas/SuggestionSummary_advisoriesSeverity_inner_open'
      type: object
    SuggestionSummary_fieldNoticeSeverity_inner_resolved:
      description: Number of field notices the current Cisco software releases are
        exposed to that are addressed by the suggested release
      example:
        medium: 8
      properties:
        medium:
          description: Number of medium impact field notices the current Cisco software
            releases are exposed to that are addressed by the suggested release
          format: int64
          type: integer
      type: object
    SuggestionSummary_fieldNoticeSeverity_inner_newOpen:
      description: Number of new field notices the current Cisco software releases
        are exposed to compared to the current Cisco software releases
      example:
        medium: 9
      properties:
        medium:
          description: Number of new medium impact field notices the current Cisco
            software releases are exposed to
          format: int64
          type: integer
      type: object
    SuggestionSummary_fieldNoticeSeverity_inner_open:
      description: Number of field notices the current Cisco software releases are
        exposed to
      example:
        medium: 6
      properties:
        medium:
          description: Number of medium impact field notices the current Cisco software
            releases are exposed to
          format: int64
          type: integer
      type: object
    SuggestionSummary_fieldNoticeSeverity_inner:
      example:
        newOpen:
          medium: 9
        open:
          medium: 6
        resolved:
          medium: 8
      properties:
        resolved:
          $ref: '#/components/schemas/SuggestionSummary_fieldNoticeSeverity_inner_resolved'
        newOpen:
          $ref: '#/components/schemas/SuggestionSummary_fieldNoticeSeverity_inner_newOpen'
        open:
          $ref: '#/components/schemas/SuggestionSummary_fieldNoticeSeverity_inner_open'
      type: object
  securitySchemes:
    OauthSecurity:
      description: These API required OAuth 2 client credentials grant type Bearer
        token
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://cloudsso.cisco.com/as/token.oauth2?
      type: oauth2
      x-kong-security-enable: false

